apiVersion: v1
kind: Secret
metadata:
  name: ai-automation-secrets
  namespace: ai-automation
type: Opaque
data:
  # Database secrets
  POSTGRES_PASSWORD: <base64-encoded-password>
  POSTGRES_USER: <base64-encoded-username>
  
  # Redis secrets
  REDIS_PASSWORD: <base64-encoded-password>
  
  # MinIO secrets
  MINIO_ROOT_USER: <base64-encoded-username>
  MINIO_ROOT_PASSWORD: <base64-encoded-password>
  
  # JWT secrets
  JWT_SECRET: <base64-encoded-secret>
  
  # AI API keys
  OPENAI_API_KEY: <base64-encoded-key>
  ANTHROPIC_API_KEY: <base64-encoded-key>
  
  # Monitoring secrets
  GRAFANA_PASSWORD: <base64-encoded-password>
